notifications:
  email: false

sudo: required

language: bash

services:
  - docker

stages:
  - build::push

jobs:
  include:
    - stage: build::push
      script:
        - docker build . -t aikupoker/torch-docker:0.0.1
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push aikupoker/torch-docker:0.0.1
